---
- name: Install ntp
  yum: name=ntp state=present

- name: Replace ntp.conf
  template: src=../../templates/ntp.conf.j2 dest=/etc/ntp.conf

- name: Ensure ntpd starts on boot
  service: name=ntpd state=started enabled=yes
